/*
 * School Management System API
 * APIs for managing branches, employees, students, receipts, etc.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: tejabhargavpodila@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SchoolManagementSystemApi);
  }
}(this, function(expect, SchoolManagementSystemApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DbUpdateRequest', function() {
      beforeEach(function() {
        instance = new SchoolManagementSystemApi.DbUpdateRequest();
      });

      it('should create an instance of DbUpdateRequest', function() {
        // TODO: update the code to test DbUpdateRequest
        expect(instance).to.be.a(SchoolManagementSystemApi.DbUpdateRequest);
      });

      it('should have the property collectionName (base name: "collectionName")', function() {
        // TODO: update the code to test the property collectionName
        expect(instance).to.have.property('collectionName');
        // expect(instance.collectionName).to.be(expectedValueLiteral);
      });

      it('should have the property query (base name: "query")', function() {
        // TODO: update the code to test the property query
        expect(instance).to.have.property('query');
        // expect(instance.query).to.be(expectedValueLiteral);
      });

      it('should have the property update (base name: "update")', function() {
        // TODO: update the code to test the property update
        expect(instance).to.have.property('update');
        // expect(instance.update).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

    });
  });

}));
